[package]
name = "rdc_connections"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.44"
log = "0.4.14"
windows = "0.21.1"
winsafe = "0.0.6"

[build-dependencies]
windows = "0.21.1"
